<?php

    $traducciones = [
        "title" => "Título",
        "user" => "Usuario",
        "login" => "Iniciar sesión",
        "password" => "Contraseña",
        "title_error" => "Error",
        "error_msg" => "Ha excedido el número permitido de inicios de sesión. &#128542;",
        "return_login" => "Volver al login",
        "remaining_attempts" => "Intentos restantes: ",
        "el_unico_final" => "El único final de la villana es la muerte",
        "cuestionario" => 'Cuestionario <br> "El unico final de la villana es la muerte"',
        "preguntas" => "Preguntas",
        "p1" => "1. ¿Quién son los dos hermanos adoptivos de Pénelope?",
        "r1.1" => "Callisto y Winter",
        "r1.2" => "Reynold y Derrik",
        "r1.3" => "Yvonne y Laila",
        "r1.4" => "Eclise y Kaden",
        "p2" => "2. ¿Cuál es la dificultad principal de Penélope al inicio del manhwa?",
        "rs" => "-Seleccionar-",
        "r2.1" => "No tiene recuerdos",
        "r2.2" => "Sus acciones bajan la barra de afecto",
        "r2.3" => "Cualquier decisión incorrecta puede llevarla a la muerte",
        "r2.4" => "No puede hablar",
        "p3" => "3. ¿Qué trata de evitar Penélope a toda costa?",
        "ra" => "Respuesta abierta",
        "p4" => "4. ¿Qué color de pelo tiene Penélope Eckhart?",
        "r4.1" => "Rubio",
        "r4.2" => "Castaño",
        "r4.3" => "Rosado",
        "p5" => "5. ¿Cuál es el objetivo principal de Penelope en la historia?",
        "r5.1" => "Convertirse en reina",
        "r5.2" => "Sobrevivir en el juego y evitar su muerte",
        "r5.3" => "Vengarse de su familia",
        "r5.4" => "Encontrar un tesoro perdido",
        "p6" => "6. ¿Cuál de los siguientes NO es un personaje masculino importante en el manhwa?",
        "r6.1" => "Callisto Regulus",
        "r6.2" => "Hermione Granger",
        "r6.3" => "Reynold Eckhart",
        "r6.4" => "Navier",
        "p7" => "7. ¿Cómo se llama la 'verdadera' hija de los Eckhart?",
        "p8" => "8. ¿Quién es el caballero exclavo que Pénelope intenta salvar?",
        "r8.1" => "Callisto",
        "r8.2" => "Yvonne",
        "r8.3" => "Eclise",
        "r8.4" => "Kaden",
        "p9" => "9. ¿Cómo llega Penélope Eckhart al mundo del juego?",
        "r9.1" => "Muere en su mundo y reencarna",
        "r9.2" => "Es absorvida por un libro",
        "r9.3" => "Se despierta dentro del juego otome",
        "r9.4" => "Viaja por un portal mágico",
        "p10" => "10. ¿Qué personaje tiene un comportamiento obsesivo hacia Penélope?",
        "Enviar" => "Enviar respuestas",
        "faltan_respuestas" => "Faltan respuestas por completar.",
        "volver_formulario" => "Volver al formulario",
        "error_pregunta6" => "Debe seleccionar al menos una opción en la pregunta 6.",
        "correcto" => "Correcto",
        "incorrecto" => "Incorrecto",
        "resultados" => "Resultados del cuestionario",
        "preguntas" => "Preguntas",
        "tu respuesta" => "Tu respuesta",
        "resultado" => "Resultado",
        "pregunta1" => "1. Hermanos adoptivos de Penélope",
        "pregunta2" => "2. Dificutad de Penélope",
        "pregunta3" => "3. ¿Qué trata de evitar Penélope?",
        "pregunta4" => "4. Color de pelo de Penélope",
        "pregunta5" => "5. ¿Cuás es su objetivo?",
        "pregunta6" => "6. No es un personaje",
        "pregunta7" => "7. Verdadera hija",
        "pregunta8" => "8. Caballero esclavo",
        "pregunta9" => "9. ¿Cómo llega al mundo?",
        "pregunta10" => "10. ¿Quién es obsesivo?",
        "puntuacion" => "Puntuación final",   
        "error" => "ERROR: Faltan respuestas por completar.",
        "marcar_opcion" => "Debe marcar al menos una opción en la pregunta 6.",
        "volver" => "Volver al formulario",
        "link_inicio" => "Inicio",
        "link_cuestionario" => "Cuestionario",
        "link_contacto" => "Contacto",
        "logout" => "Cerrar Sesión",
        "bienvenido" => "Bienvenido a la Web, ",
        "informacion" => "Información del Manhwa",
        "titulo" => "El único final de la villana es la muerte",
        "parrafo1" => "'El único final de la villana es la muerte' 
        es la historia de Penélope Eckart, una joven que reencarna<br> 
        en el cuerpo de la villana de un juego otome de dificultad máxima, 
        quien está destinada a morir sin<br> importar sus acciones. 
        La trama gira en torno a su lucha por sobrevivir y cambiar<br> el fatal destino que el juego le impone.",
        "personajes" => "Personajes Principales",
        "lista_personajes" => "Lista de Personajes",
        "personaje_penelope" => "<b>Penelope Eckart:</b>  Es el personaje principal 
        que renace como la villana<br> del juego otome que jugaba. Su objetivo es 
        sobrevivir a las múltiples<br> consecuencias de su nuevo papel y ganarse el 
        favor de los otros personajes.",
        "personaje_callisto" => "<b>Callisto Regulus (Príncipe Heredero):</b>Un personaje despiadado y poderoso.<br> 
        Penelope debe navegar por su naturaleza volátil y evitar ser ejecutada<br> mientras busca asegurar 
        su afecto para garantizar su supervivencia.",
        "personaje_reynold" => "<b>Reynold Eckart:</b> El segundo hijo de la casa Eckart.<br> 
        A diferencia de su hermano mayor, es más amable y protector con Penelope,<br>
        desarrollando sentimientos genuinos hacia ella.",
        "personaje_derrick" => "<b>Derrick Eckart:</b> El primer hijo de la casa Eckart.<br> 
        Es conocido por su personalidad fría y calculadora. Aunque inicialmente ve a Penelope<br>
        como una molestia, eventualmente muestra un lado más suave hacia ella.",
        "personaje_winter" =>  "<b>Winter Vinter:</b> El mago y duque.<br> 
        Es un personaje enigmático con una gran influencia en la corte. A pesar de su<br> 
        apariencia distante, tiene un interés particular en Penelope y su bienestar.",
        "personaje_eclise" => "<b>Eclise:</b> El esclavo de Penelope.<br> 
        A pesar de su estatus, muestra una lealtad inquebrantable hacia ella y desempeña un papel crucial<br>
        en su lucha por sobrevivir en el mundo del juego.",
        "contacto" => "Contacto",
        "informacion_contacto" => "Información de Contacto",
        "email" => "email:",
        "titulo_inicio" => "El único final de la villana es la muerte",
    ];

?>